li---
title: "Basics"
author: "Joseph Kim"
date: "April 15, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Packages

```{r}
# import packages
library(quantmod)
library(plyr)
library(xts)
```

## Data

```{r}
getSymbols("AAPL", src = "yahoo", from = as.Date('2018-01-01'), to = as.Date('2018-05-20'))
```

## Indicators 

```{r}
# calculates derivative of closing prices
# applies specifically to moving averages
discreteDeriv <- function(data, shift) {
  discrete <- rep(NA, shift)
  for (i in 1:length(data)-1) {
    discrete <- append(discrete, data[i+1]-data[i])
  }
  return(discrete)
}
```

```{r}
# get sma data
close_aapl <- data.frame(AAPL$AAPL.Close)
sma_aapl <- SMA(close_aapl, n = 10)
sma_raw_aapl <- sma_aapl[complete.cases(sma_aapl),]
```

```{r}
# calculate derivative of sma, 10 day average
sma_deriv_aapl <- discreteDeriv(sma_raw_aapl, 10)
sma_deriv_raw_aapl <- sma_deriv_aapl[complete.cases(sma_deriv_aapl)]
```

```{r}
# calculate 2nd derivate of sma
sma_2deriv_aapl <- discreteDeriv(sma_deriv_raw_aapl, 11)
```

```{r}
# store sma and derivative of sma
sma_func <- data.frame(cbind(sma_aapl, sma_deriv_aapl, sma_2deriv_aapl))
```

```{r}
# convert derivatve to binary
bin_deriv <- sma_func$sma_deriv_aapl
bin_deriv[bin_deriv > 0] <- 1
bin_deriv[bin_deriv <= 0] <- 0

# convert 2nd derivate to binary
bin_2deriv <- sma_func$sma_2deriv_aapl
bin_2deriv[bin_2deriv > 0] <- 1
bin_2deriv[bin_2deriv <= 0] <- 0

# find equilibrium points
equil_pts <- c(which(diff(bin_deriv)!=0))
equil_pts_deriv_shift <- equil_pts + 1
equil_dates <- as.Date(row.names(close_aapl)[equil_pts])

# categorize buy, sell signal at equilibrium dates
equil_dates_2deriv <- bin_2deriv[equil_pts_deriv_shift]
equil_signal <- ifelse(equil_dates_2deriv == 1, "buy", "sell")

# create xts objects for buy and sell dates
buy_sell_dates <- xts(x = equil_dates_2deriv, order.by = as.Date(equil_dates))
buy_dates <- rownames(data.frame(buy_sell_dates[buy_sell_dates == 1]))
sell_dates <- rownames(data.frame(buy_sell_dates[buy_sell_dates == 0]))
```

## Plot

```{r}
# plot equilibrium pts
x_vline_buy <- xts(rep(TRUE, length(as.Date(buy_dates))), as.Date(buy_dates))
x_vline_sell <- xts(rep(TRUE, length(as.Date(sell_dates))), as.Date(sell_dates))
chartSeries(x = AAPL, subset = '2018-01-01::2018-05-20', type = "candlesticks", theme = chartTheme("white"), up.col = "green", dn.col = "red") 
addSMA(n = 10)
addTA(x_vline_buy, on = -1, col = "lightblue", border='darkgreen')
addTA(x_vline_sell, on = -1, col = "gold", border='darkred')
```

